#CRIE UM PROGRAMA QUE SIMULE O FUNCIONAMENTO DE UM CAIXA ELETRONICO. NO INICIO PERGUNTE AO USUARIO QUAL O VALOR
# A SER SACADO NUMERO INTEIRO E O PROGRAMA VAI INFORMAR QUANTS CEDULAS DE CADA VALOR SERÃO ENTREGUES
# OBS: CONSIDERE QUE O CAIXA POSSUI CEDULAS DE 50, 20, 10 E 1 REAL