#CRIE UM PROGRAMA QUE LEIA O NOME E O PREÇO DE VÁRIOS PRODUTOS. O PROGRAMA DEVERA PERGUNTAR SE O USUáRIO VAI
# CONTINUAR NO FINAL MOSTRA: #QUAL É  O TOTAL GASTO NA COMPRA, QUANTOS PRODUTOS CUSTAM MAIS DE R$ 1000,
# QUAL É O NOME DO PRODUTO MAIS BARATO.